# Site settings
title:       boobo94
logo_title:  boobo94
email:       militaru.bogdanalexandru@gmail.com
author:      Bogdan Alexandru Militaru
description: "Discover more about me. Learn about web, technology, web services, artificial intelligence, servers, cloud, amazon, alexa skills, tutorials. Check it now!"
baseurl:     ""
url:         "https://boobo94.github.io"
date_format: "%b %-d, %Y"
header_pages:
 - about.md
 - portfolio.html
 - contact.html

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-113538337-2
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             true
show_related_posts:   false
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false
# Preview image for social media aka og:image and twitter:image
post_preview_image: true

# Facebook Page integration
# (for instant articles and other stuff)
fb_page: false
fb_page_id:

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# txtpen post comments
# (leave blank to disable txtpen)
txtpen_sitename:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: boobo94
reddit_username:
bitbucket_username:
stackoverflow_id: 4471897
twitter_username: militaru_bogdan
skype_username: boobo_boobo94
steam_nickname:
google_plus_id:
linkedin_username: bogdan-alexandru-militaru-bb801697
angellist_username:
medium_id: boobo94
bitcoin_url:
paypal_url:
flattr_button:
telegram_username:
vk_id:

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: true

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /:categories/:title/
paginate:     5
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

collections:
  category:
    output: true

  portfolio:
    output: true
    permalink: /portfolio/:path/

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
